# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N0a_QaVx-nyHsCSWTbQZBNkESy7I_EI_
"""

import numpy as np
from matplotlib import pyplot as plt

ys = 200 + np.random.randn(100)
x = [x for x in range(len(ys))]

plt.plot(x, ys, '-')
plt.fill_between(x, ys, 195, where=(ys > 195), facecolor='g', alpha=0.6)

plt.title("Sample Visualization")
plt.show()

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import csv
iris=pd.read_csv("/Iris.csv")
print(iris)

print(iris.shape)

print(iris.describe())

print(iris.isna().sum())
print(iris.describe())

iris.head()

iris.head(150)

iris.head(150)

iris.hist()
plt.show()

import matplotlib.pyplot as plt
plt.figure(1)
plt.boxplot([iris['SepalLengthCm']])
plt.figure(2)
plt.boxplot([iris['SepalWidthCm']])
plt.show()



iris.plot(kind ='density',subplots = True, layout =(3,3),sharex = False)

iris.plot(kind ='box',subplots = True, layout =(2,5),sharex = False)

X = iris['SepalLengthCm'].values.reshape(-1,1)
print(X)

X = iris['SepalLengthCm'].values.reshape(-1,1)
print(X)

corr_mat = iris.corr()
print(corr_mat)

from sklearn.linear_model import LogisticRegression 
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier

train, test = train_test_split(iris, test_size = 0.25)
print(train.shape)
print(test.shape)

train_X = train[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm',
                 'PetalWidthCm']]

test_X = test[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm',
                 'PetalWidthCm']]

test_y = test.Species

train_X.head()

test_y.head()

test_y.head()

from sklearn.metrics import confusion_matrix
confusion_mat = confusion_matrix(test_y,prediction)
print("Confusion matrix: \n",confusion_mat)